# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7
  slack: circleci/slack@4.5.1

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - slack/notify:
          channel: circleci
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: circleci
          event: pass
          template: basic_success_1
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run: npm install
      - run: npm run test:unit
      - slack/notify:
          channel: circleci
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: circleci
          event: pass
          template: basic_success_1

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build_and_test: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
      - test
      # - test:
      #     requires:
      #       - build

